version: '3'
services:
  setup:
    build: .
    image: haskell102:latest
    command: make -C 00_setup
  section_1:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS="check 1"
  section_2:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS="check 2"
  section_3:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS="check 3"
  section_4:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS="check 4"
  section_5:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS="check 5"
  play:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS=play
    tty: true
  solve:
    build: .
    image: haskell102:latest
    command: make -C 01_mastermind ARGS=solve
