version: '3'

x-haskell-docker-setup: &generic-haskell-runtime
  image: google/haskell-trainings
  build: .
  # Preserve terminal colors when running containers
  # https://github.com/docker/compose/issues/2231#issuecomment-425135985
  tty: yes

# When setting the CLI mode, run the command docker-compose run SERVICE_NAME
# https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose/36265910#36265910 
# Run with docker-compose run SERVICE
# MUST ENABLE IT IN THE SERVICE BELOW
x-docker-cli-mode: &docker-cli-mode
  entrypoint: /bin/sh -c
  command: bash

####
#### you can execute the code as follows:
#### 
####      docker-compose up --build 0x_yyyyy 
####
services:

  00_setup:
    <<: [ *generic-haskell-runtime ]
    #<<: [ *docker-cli-mode ]
    command: make -C 00_setup

  01_functions:
    <<: [ *generic-haskell-runtime ]
    command: make -C 01_functions

  02_datatypes:
    <<: [ *generic-haskell-runtime ]
    # You can run in CLI mode with "docker-compose run 02_datatypes"
    #<<: [ *docker-cli-mode ]
    command: make -C 02_datatypes

  03_lists:
    <<: [ *generic-haskell-runtime ]
    command: make -C 03_lists

  04_abstractions:
    <<: [ *generic-haskell-runtime ]
    command: make -C 04_abstractions

  05_maybe:
    <<: [ *generic-haskell-runtime ]
    command: make -C 05_maybe

  06_rps:
    <<: [ *generic-haskell-runtime ]
    command: make -C 06_rps
